project:
  type: website
  output-dir: docs

website:
  title: "NHL Skater Performance Analytics"
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd

      - section: "Background"
        contents:
          - about.qmd
          - data.qmd
          - preprocessing.qmd
          - descriptive.qmd
          - eda.qmd

      - section: "Research Question 1"
        contents:
          - r1.qmd
          - rq1_details.qmd

      - section: "Research Question 2"
        contents:
          - r2.qmd
          - rq2_details.qmd

      - section: "Research Question 3"
        contents:
          - r3.qmd
          - rq3_details.qmd
          
      - section: "Results & Conclusion"
        contents:
          - results.qmd
          - conclusion.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show / Hide Code"
    smooth-scroll: true
    css: style.css
